export const LABELS = {
  app: {
    name: "ShiftModule",
  },
  common: {
    loading: "Učitavanje...",
    retry: "Pokušaj ponovno",
    search: "Pretraži",
    save: "Spremi",
    cancel: "Odustani",
    close: "Zatvori",
    continue: "Nastavi",
    back: "Natrag",
    delete: "Obriši",
    edit: "Uredi",
    create: "Kreiraj",
    import: "Uvezi",
    details: "Detalji",
    noResults: "Nema rezultata",
    unauthorized: "Nemate pristup ovoj stranici.",
    notFound: "Tražena stranica nije pronađena.",
  },
  auth: {
    title: "Prijava",
    subtitle: "Modul za promjenu grupa",
    email: "E-mail",
    password: "Lozinka",
    signIn: "Prijavi se",
    invalidCredentials: "Neispravni podaci za prijavu.",
    networkError: "Provjerite internetsku vezu i pokušajte ponovno.",
    loginFailed: "Prijava trenutno nije dostupna. Pokušajte ponovno kasnije.",
  },
  nav: {
    home: "Početna",
    dashboard: "Dashboard",
    requests: "Zahtjevi",
    groups: "Grupe",
    settings: "Postavke",
    courses: "Kolegiji",
    students: "Studenti",
    studyMajors: "Programi",
    schedule: "Raspored",
    notifications: "Obavijesti",
    profile: "Profil",
    reports: "Izvještaji",
    myCourses: "Moji Kolegiji",
  },
  pages: {
    adminDashboard: "Admin dashboard",
    adminStudents: "Studenti",
    adminCourses: "Predmeti",
    professorCourses: "Moji kolegiji",
    professorRequests: "Zahtjevi za zamjenu",
    professorAutoLog: "Automatska obrada",
    studentCourses: "Tečajevi",
    studentRequests: "Moji zahtjevi",
    confirmSwap: "Potvrda zamjene",
  },
  status: {
    pending: "Na čekanju",
    approved: "Odobreno",
    rejected: "Odbijeno",
    autoResolved: "Automatski riješeno",
    full: "Puno",
    warning: "Skoro puno",
    available: "Dostupno",
    manual: "Ručno",
  },
} as const;
